# Generated by Django 2.1.5 on 2019-01-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='esheets.Student'),
            preserve_default=False,
        ),
    ]
