# Generated by Django 2.1.5 on 2019-01-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esheets', '0004_auto_20190112_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esheets.TestQuestion'),
        ),
    ]
